nbviewer: "https://nbviewer.jupyter.org/github/taruma/hidrokit-nb/blob/master"
github: "https://github.com/taruma/hidrokit-nb/blob/master"
rawgithub: "https://raw.githubusercontent.com/taruma/hidrokit-nb/master"
googlecolab: "https://colab.research.google.com/github/taruma/hidrokit-nb/blob/master"