# Site setting
title: Hidrokit Notebook
description: Kumpulan jupyter notebook hidrologi
baseurl: ""
url: ""

# Theme
theme: "just-the-docs"
# remote_theme: pmarsceill/just-the-docs

# Theme settings
# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Punya ide untuk situs ini?":
    - "//github.com/taruma/hidrokit-nb/issues/new/choose"


